// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }






// import Navbar from "@/components/layout/Navbar";
// import Footer from "@/components/home/Footer";
// import "./globals.css";

// export const metadata = {
//   title: "Vibely",
//   description:
//     "Publish TikTok videos securely using the official TikTok Content Posting API.",
// };

// export default function RootLayout({
//   children,
// }) {
//   return (
//     <html lang="en">

//       <body>

//         <Navbar />

//         {children}

//         <Footer />

//       </body>

//     </html>
//   );
// }





import Footer from "@/components/public/Footer";
import "./globals.css";

import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "sonner";

export const metadata = {
  metadataBase: new URL("https://vibely.egrif.online"),

  title: {
    default: "Vibely",
    template: "%s | Vibely",
  },

  description:
    "Vibely is a secure TikTok publishing platform that allows creators and businesses to upload and manage videos using the official TikTok API.",

  keywords: [
    "TikTok",
    "TikTok API",
    "Content Posting API",
    "Video Upload",
    "Social Media",
    "Vibely",
  ],

  authors: [
    {
      name: "Vibely",
    },
  ],

  creator: "Vibely",

  publisher: "Vibely",

  robots: {
    index: true,
    follow: true,
  },

  openGraph: {
    title: "Vibely",
    description:
      "Official TikTok publishing platform for creators.",
    url: "https://vibely.egrif.online",
    siteName: "Vibely",
    locale: "en_US",
    type: "website",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "Vibely",
    description:
      "Upload videos using the official TikTok API.",
    images: ["/og-image.png"],
  },

  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">

      <body>

        <AuthProvider>
          <Toaster richColors position="top-right" />
          {children}
          <Footer />
        </AuthProvider>

      </body>

    </html>
  );
}